[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jax-ml-template"
version = "0.1"
description="A minimal starter kit for JAX-based machine learning projects."
dynamic = ["dependencies"] 